# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/watermark/vivado/MIPS.cache/wt [current_project]
set_property parent.project_path C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/watermark/vivado/MIPS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/watermark/vivado/MIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/water2.mem
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/water1.mem
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/image2.mem
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/image1.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/GUI.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/PixCounter.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/VGAInterface.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/alu.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/arithmetic.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/counter.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/data_memory.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/inst_memory.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/logic.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/mips.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/pc.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/register_file.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/signextend.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/processor/splitter.v
  C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/vga/Graphics.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/watermark/vivado/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jelon/Documents/Workspaces/School/ImageWatermark/FPGA/watermark/vivado/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Graphics -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Graphics.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Graphics_utilization_synth.rpt -pb Graphics_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
